### ISSUE TITLE
参加者の回答専用のブランチおよびディレクトリ作成

### ISSUE THREAD

**Issue by stqp** [n-guitar/go_study#15]
【要望】
　1. 参加者用の回答コミット用のブランチ
　2. 参加者の回答置き場のディレクトリ

【1.について】
　ブランチを作成してください。
　ブランチ名は `<user_name>_ans` という命名規則を希望します

　例：tokuda_ans

【2.について】
　リポジトリのトップに `ans` というディレクトリを作ってほしいです。
　そこに各自の回答コードをコミットしたいです！

　例：ans/tokuda

**Comment by n-guitar** [comment]
作成完了
